In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [3]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [4]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [5]:
# Retrieve the element at the second column, second row
# row x column
matrix[1, 1]

5

In [6]:
# Retrive the first 2 elements of the last 2 rows
# row x column
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [7]:
should_be_included = [True, False, True]
a[should_be_included]

array([1, 3])

# Vectorized Operations

In [8]:
# If I wanted to add 1 to every element in a list, without numpy, I can't
# Add 1 to the list, as it will result in a type error.
original_array = [1, 2, 3, 4, 5]

try:
    original_array + 1
except TypeError as e:
    print("An error Occured!")
    print(f"TypeError: {e}")

An error Occured!
TypeError: can only concatenate list (not "int") to list


> In order to add 1 to each element of a list, I would need to
create a for loop or list comprehension to iterate through the list.

In [9]:
array_with_one_added = []

for n in original_array:
    array_with_one_added.append(n+1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [10]:
array_with_one_added = [n+1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [11]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [12]:
my_array = np.array([-3, 0, 3, 16])

In [13]:
print("my_array == {}".format(my_array))
print("my_array -5 == {}".format(my_array - 5))
print("my_array * 4 == {}".format(my_array * 4))
print("my_array / 2 == {}".format(my_array / 2))
print("my_array ** 2 == {}".format(my_array ** 2))
print("my_array % 2 == {}".format(my_array % 2))

my_array == [-3  0  3 16]
my_array -5 == [-8 -5 -2 11]
my_array * 4 == [-12   0  12  64]
my_array / 2 == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2 == [1 0 1 0]


# Two Methods to Filter Values in an Array

> I can perform comparisons using relational operators with arrays!
The first method to perform comparisons is to compare the __entire__
array variable against some value.

In [14]:
my_array = np.array([-3, 0, 3, 16])

print("my_array == {}".format(my_array))
print("my_array == 3 == {}".format(my_array == 3))
print("my_array >= 0 == {}".format(my_array >= 0))
print("my_array < 10 == {}".format(my_array < 10))

my_array == [-3  0  3 16]
my_array == 3 == [False False  True False]
my_array >= 0 == [False  True  True  True]
my_array < 10 == [ True  True  True False]


> I can also filter values by calling the variable name with
the array boolean expression inside of square brackets.

In [15]:
my_array[abs(my_array) == 3]

array([-3,  3])

In [16]:
my_array[my_array > 0]

array([ 3, 16])

In [17]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [18]:
my_array % 2

array([1, 0, 1, 0])

In [19]:
result = my_array % 2
result == 0

array([False,  True, False,  True])

> I can create an array of boolean values from the original array
and use the boolean array to filter for values. __UNDER THE HOOD__

In [20]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]
print(step_3)

[ 0 16]


In [21]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


# Array Creation
> Numpy provides several methods for creating arrays I'll learn about
them here.

`np.random.randn` 
> Returns values from the standard normal distribution, 0-1.
> The first parameter creates an array of (d1, d2,....dn). I don't
> yet know how to read anything past 2~3 dimensions. More exposure!

In [40]:
# With the arguments passed below, the `np.random.randn' function
# Creates 2, 3 x 3 arrays!
np.random.randn(2, 3, 3)

array([[[ 0.16444364,  0.62133805, -0.60624554],
        [ 0.84900509,  2.08998087,  0.6096297 ],
        [-0.64775087, -2.09505693,  0.04718874]],

       [[-0.57346668,  1.53088656, -0.65060979],
        [ 1.89533977, -0.26609702, -0.45634747],
        [-1.06979126, -0.84913703, -0.87117273]]])

In [39]:
np.random.randn(10)

array([ 2.18847954, -1.67367571,  0.89174388, -0.51177213,  0.20207421,
       -1.63611558, -0.8894505 , -1.36810229, -1.45371573, -0.9296372 ])

In [36]:
mu = 100
sigma = 30

# This formula is inside the np.random.randn docstring!!
sigma * np.random.randn(20) + mu

array([ 95.213266  ,  61.82861691,  34.81041834,  98.61799515,
        69.92274119, 127.94086864,  82.78369459,  92.2672414 ,
       135.58134085, 103.06459291,  75.06913603, 110.26483485,
       148.54433842,  36.3932994 , 153.33850755,  93.84497549,
       112.37075224, 118.17919573, 107.80608861,  97.23018239])

> Three functions: `zeros`, `ones`, `full` allow me to create numpy
arrays.

> By reading the `np.ones` docstring, I discovered there are more
numpy functions I can use to generate a numpy array. `empty` and `ones_like`.

In [33]:
# It's important to read docs/doc strings when working with new
# New functions. Here I did not know that `np.zeros` would not take
# 2 dimensions outside of parentheses. The '`zeros` function takes
# either an int OR a TUPLE OF INTS! module.function_name? <-----
# np.zeros?
print(np.zeros(9))
print('\n')
print(np.zeros((3, 3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [66]:
# Similar to the `np.zeros` function, the `np.ones` function
# Accepts an int OR a tuple of ints. The `np.ones` function creates
# an array of 1's of datatype float.
# np.ones?
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
# The `np.full` function accepts similar parameters as the other array
# creator/creation functions. The `np.full` function accepts another
# Argument in addition to array shape - Fill Value!
# np.full?
np.full((3, 3), 20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

Numpy `arange` function

Additional: `numpy.linspace`,`numpy.ogrid`,`numpy.mgrid`

In [65]:
# np.arange?
# Unlike Python's built-in function, `range`, `np.arange`
# Can accept float step values. Example. Step size 00.10
# I can specify the Start, Stop (non-inclusive), and Step size.
np.arange(1, 10, .1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [58]:
# `np.arange` cannot broadcast along multiple dimensions
# All values must be passed in a Series. Then, using the `reshape`
# Function reshape the array with my desired dimensions.
np.full(9, np.arange(1,10)).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
# I can use the `np.linspace` function to create ranges of numbers
# With one unique parameter -> length. Returns an array with dtype
# float. The `np.linspace` function returns evenly spaced numbers
# Over a specified interval. 0 to 10, 5 even spaces.
np.linspace?
np.linspace(0, 10, 5) #MINIMUM 0, Maxiumum[INCLUSIVE] 10, length 5

In [71]:
np.ogrid?

In [72]:
np.mgrid?

> Also: `np.geomspace` `np.logspace`

# Array Methods
> I can perform mathematical operations with built-in methods!

In [73]:
a = np.array([1, 2, 3, 4, 5])

In [81]:
# I can use the `np.min` function to select the minimum value
# of an array OR minimum along an axis - row/column
# np.min?
a.min()

1

In [82]:
# Similar functionality as `np.min` except with MAX value
# np.max?
a.max()

5

In [85]:
# Similar functionality as `np.min` and `np.max`, but averages
# There is an interesting note in `np.mean` docstring.
# In single precision 'mean' can be inaccurate. 
# np.float32 < np.float64 accuracy.
# np.mean?
a.mean()

3.0

In [88]:
# Similar functionality as `np.min`, `np.max`, `np.mean`, but summation.
# np.sum?
a.sum()

15

In [91]:
# Similar to `np.min`, `np.max`, `np.mean`, `np.sum`, but std. dev.
# Docstring: Computing the standard deviation in float64 is more accurate:
# np.std?
np.std(a, dtype=np.float64)

1.4142135623730951